import Head from 'next/head'
import Link from 'next/link';
import { useContext, useEffect, useState } from 'react'
import { appCtx } from '../../Context/AppContext';
import { songCtx } from '../../Context/SongContext'
import SoundPlayer from '../SoundPlayer'

export default function Layout({ children,  }) {
    const { translate } = useContext(appCtx);
    const [pageTitle, setPageTitle] = useState(`${translate.systemTitle}`);
    const { currentMusic: { music }, playingMusic: { playingMusicId }, soundPlayer: { showPlayer }, isPlaying: { playing } } = useContext(songCtx);

    useEffect(() => {
        if (!showPlayer) {
            setPageTitle(`${translate.systemTitle}`);
        } else {
            setPageTitle(`${playing ? translate.tab.play : translate.tab.pause}${music.music[playingMusicId?.index]?.name}`)
        }
    }, [showPlayer, playing, music.music, playingMusicId?.index])

    return (
        <>
            <Head>
                <meta charSet='utf-8' />
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <title>{pageTitle}</title>

            </Head>
            {children}
            {showPlayer && <SoundPlayer />}
        </>
    )
}